### ISSUE TITLE
[AV-Wiki] Fail to update metadata

### ISSUE THREAD

**Issue by jarderiu** [alxpnt2/PlexJav18.bundle#26]
[AV-Wiki] Fail to update metadata, some examples:
`SUWK-011, SPLY-012, START-015`

[com.plexapp.agents.jav18.log](https://github.com/alxpnt2/PlexJav18.bundle/files/14251652/com.plexapp.agents.jav18.log)

**Comment by alxpnt2** [comment]
I just pushed an update that fixes some of the site parsers. I was able to match all of your titles here. I suspect that you initially tried to match these titles while AV-Wiki was the only service that had them available. I don't use AV-Wiki to provide metadata (only to get content IDs) since it doesn't have as much information as the other sites and all of it is in Japanese. 

Let me know if you're still having issues.
